# solr default config
all:
  solr:
#    models:
#      TableName:
#        index:
#          host: "localhost"
#          port: "8983"
#          path: "/solr"

    index:
      host: "localhost"
      port: "8983"
      path: "/solr"

