<?php

/**
 * BaseThread
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Posts
 * 
 * @method string              getTitle() Returns the current record's "title" value
 * @method Doctrine_Collection getPosts() Returns the current record's "Posts" collection
 * @method Thread              setTitle() Sets the current record's "title" value
 * @method Thread              setPosts() Sets the current record's "Posts" collection
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseThread extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('thread');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Post as Posts', array(
             'local' => 'id',
             'foreign' => 'thread_id'));
    }
}