<?php

/**
 * BaseStory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $slug
 * @property clob $body
 * 
 * @method string getSlug() Returns the current record's "slug" value
 * @method clob   getBody() Returns the current record's "body" value
 * @method Story  setSlug() Sets the current record's "slug" value
 * @method Story  setBody() Sets the current record's "body" value
 * 
 * @package    ##PROJECT_NAME##
 * @subpackage model
 * @author     ##AUTHOR_NAME##
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('story');
        $this->hasColumn('slug', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('body', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'body',
             ),
             ));
        $solr0 = new Doctrine_Template_Solr(array(
             'fields' => 
             array(
              0 => 'body',
             ),
             ));
        $this->actAs($i18n0);
        $this->actAs($solr0);
    }
}